USE master;
GO

IF DB_ID('EmployeeDB') IS NOT NULL
BEGIN
    ALTER DATABASE EmployeeDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE EmployeeDB;
END
GO

CREATE DATABASE EmployeeDB;
GO

USE EmployeeDB;
GO